require:
  - rubocop-rspec
AllCops:
  NewCops: enable
Layout/CommentAnnotation:
  AllowedPatterns:
    - "# frozen_string_literal: true"

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  AllowShebang: true
