#!/usr/bin/env ruby

require_relative 'toy_robot'

dispatcher = ToyRobot::Dispatcher.new

commands = dispatcher.read_commands_from_file(file_path: ARGV[0])

dispatcher.run(commands: commands) if $PROGRAM_NAME == __FILE__
