#!/usr/bin/env ruby

require_relative 'toy_robot'

dispatcher = ToyRobot::Dispatcher.new

commands = dispatcher.read_commands_from_file(ARGV[0])

dispatcher.execute_commands(commands) if $PROGRAM_NAME == __FILE__
